// @ts-nocheck
import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "hi" | "raj";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Comprehensive translations
const translations = {
  en: {
    // App Header & Navigation
    "app.title": "University of Edinburgh",
    "app.title.hindi": "University of Edinburgh",
    "academic.year": "Academic Year 2025-26",
    "quick.stats": "Quick Stats",
    "attendance": "Attendance",
    "fees.paid": "Fees Paid",
    "today.classes": "Today's Classes",
    "online": "Online",
    "light.mode": "Light Mode",
    "dark.mode": "Dark Mode",
    "sign.out": "Sign Out",
    "confirm.sign.out": "Confirm Sign Out",
    "sign.out.message": "Are you sure you want to sign out from the University of Edinburgh portal?",
    "cancel": "Cancel",
    "notifications": "Notifications",
    "mark.all.read": "Mark All as Read",
    "home": "Home",
    
    // Navigation Items
    "nav.overview": "Overview",
    "nav.dashboard": "Dashboard",
    "nav.academic": "Academic",
    "nav.personal.info": "Personal Info",
    "nav.examination.record": "Examination Record",
    "nav.schedule": "Schedule",
    "nav.resources": "Resources",
    "nav.fees": "Fees",
    "nav.system": "System",
    "nav.settings": "Settings",
    
    // Dashboard
    "dashboard.welcome": "Welcome back, Arjun!",
    "dashboard.overview": "Here's what's happening in your academic journey today.",
    "attendance.progress": "Attendance Progress",
    "fee.payment": "Fee Payment",
    "assignments": "Assignments",
    "recent.activities": "Recent Activities",
    "upcoming.events": "Upcoming Events",
    "quick.actions": "Quick Actions",
    "view.schedule": "View Schedule",
    "check.fees": "Check Fees",
    "download.results": "Download Results",
    "academic.performance": "Academic Performance",
    "current.semester": "Current Semester",
    "overall.grade": "Overall Grade",
    "class.rank": "Class Rank",
    
    // Personal Info
    "personal.information": "Personal Information",
    "student.details": "Student Details",
    "full.name": "Full Name",
    "roll.number": "Roll Number",
    "course": "Course",
    "section": "Section",
    "admission.number": "Admission Number",
    "date.of.birth": "Date of Birth",
    "gender": "Gender",
    "blood.group": "Blood Group",
    "contact.information": "Contact Information",
    "email": "Email",
    "phone": "Phone",
    "address": "Address",
    "parent.guardian.info": "Parent/Guardian Information",
    "father.name": "Father's Name",
    "mother.name": "Mother's Name",
    "guardian.phone": "Guardian Phone",
    "emergency.contact": "Emergency Contact",
    "edit.profile": "Edit Profile",
    "save.changes": "Save Changes",
    
    // Examination Record
    "examination.records": "Examination Records",
    "exam.results": "Exam Results",
    "select.exam": "Select Exam",
    "first.term": "First Term 2025",
    "second.term": "Second Term 2025",
    "annual.exam": "Annual Exam 2025",
    "search.subject": "Search subject...",
    "subject": "Subject",
    "marks.obtained": "Marks Obtained",
    "total.marks": "Total Marks",
    "percentage": "Percentage",
    "grade": "Grade",
    "download.transcript": "Download Transcript",
    "view.detailed.report": "View Detailed Report",
    "exam.statistics": "Exam Statistics",
    "highest.score": "Highest Score",
    "average.score": "Average Score",
    "subjects.passed": "Subjects Passed",
    
    // Schedule
    "schedule.calendar": "Schedule & Calendar",
    "today.schedule": "Today's Schedule",
    "upcoming.assignments": "Upcoming Assignments",
    "class.timetable": "Class Timetable",
    "monday": "Monday",
    "tuesday": "Tuesday",
    "wednesday": "Wednesday",
    "thursday": "Thursday",
    "friday": "Friday",
    "saturday": "Saturday",
    "sunday": "Sunday",
    "time": "Time",
    "assignment": "Assignment",
    "due.date": "Due Date",
    "status": "Status",
    "pending": "Pending",
    "completed": "Completed",
    "submitted": "Submitted",
    
    // Resources
    "learning.resources": "Learning Resources",
    "digital.library": "Digital Library",
    "search.resources": "Search resources...",
    "textbooks": "Textbooks",
    "reference.books": "Reference Books",
    "online.materials": "Online Materials",
    "practice.papers": "Practice Papers",
    "download": "Download",
    "view": "View",
    "recent.downloads": "Recent Downloads",
    
    // Fees
    "fee.management": "Fee Management",
    "fee.overview": "Fee Overview",
    "total.annual.fee": "Total Annual Fee",
    "paid.amount": "Paid Amount",
    "pending.amount": "Pending Amount",
    "payment.history": "Payment History",
    "quick.pay": "Quick Pay",
    "pay.now": "Pay Now",
    "download.receipt": "Download Receipt",
    "payment.due": "Payment Due",
    "fee.structure": "Fee Structure",
    "tuition.fee": "Tuition Fee",
    "exam.fee": "Exam Fee",
    "library.fee": "Library Fee",
    "sports.fee": "Sports Fee",
    
    // Settings
    "settings": "Settings",
    "account.settings": "Account Settings",
    "profile.picture": "Profile Picture",
    "change.password": "Change Password",
    "current.password": "Current Password",
    "new.password": "New Password",
    "confirm.password": "Confirm Password",
    "preferences": "Preferences",
    "language": "Language",
    "theme": "Theme",
    "system": "System",
    "light": "Light",
    "dark": "Dark",
    "notifications.settings": "Notification Settings",
    "email.notifications": "Email Notifications",
    "push.notifications": "Push Notifications",
    "sms.notifications": "SMS Notifications",
    "about.studiq": "About StudIQ",
    "company.info": "Company Information",
    "version": "Version",
    "support": "Support",
    "privacy.policy": "Privacy Policy",
    "terms.of.service": "Terms of Service",
    
    // Common Actions
    "save": "Save",
    "edit": "Edit",
    "delete": "Delete",
    "update": "Update",
    "refresh": "Refresh",
    "loading": "Loading...",
    "search": "Search",
    "filter": "Filter",
    "sort": "Sort",
    "export": "Export",
    "import": "Import",
    "print": "Print",
    "share": "Share",
    "copy": "Copy",
    "close": "Close",
    "back": "Back",
    "next": "Next",
    "previous": "Previous",
    "submit": "Submit",
    "reset": "Reset",
    "clear": "Clear",
    
    // Subjects
    "english": "Technical Communication",
    "hindi": "Operating Systems",
    "mathematics": "Advanced Calculus",
    "science": "Data Structures",
    "social.science": "Social Data Structures",
    "physics": "Physics",
    "chemistry": "Chemistry",
    "biology": "Biology",
    "geography": "Geography",
    "history": "History",
    "civics": "Civics",
    "computer.science": "Computer Data Structures",
    "physical.education": "Physical Education",
    "art": "Art",
    "music": "Music",
    
    // Messages & Alerts
    "success.saved": "Changes saved successfully!",
    "error.occurred": "An error occurred. Please try again.",
    "confirm.delete": "Are you sure you want to delete this item?",
    "no.data.found": "No data found",
    "loading.please.wait": "Loading, please wait...",
    "session.expired": "Your session has expired. Please log in again.",
    "connection.error": "Connection error. Please check your internet connection.",
    "urgent": "Urgent",
    
    // Student Info
    "student.name": "Arjun Singh",
    "student.class": "CS Section A",
    "student.roll": "Roll No. 015"
  },
  
  hi: {
    // App Header & Navigation
    "app.title": "राजस्थान पब्लिक स्कूल",
    "app.title.hindi": "राजस्थान पब्लिक स्कूल",
    "academic.year": "शैक्षणिक वर्ष 2025-26",
    "quick.stats": "त्वरित आंकड़े",
    "attendance": "उपस्थिति",
    "fees.paid": "फीस भुगतान",
    "today.classes": "आज की कक्षाएं",
    "online": "ऑनलाइन",
    "light.mode": "लाइट मोड",
    "dark.mode": "डार्क मोड",
    "sign.out": "साइन आउट",
    "confirm.sign.out": "साइन आउट की पुष्टि करें",
    "sign.out.message": "क्या आप वाकई राजस्थान पब्लिक स्कूल के छात्र पोर्टल से साइन आउट करना चाहते हैं?",
    "cancel": "रद्द करें",
    "notifications": "सूचनाएं",
    "mark.all.read": "सभी को पढ़ा हुआ चिह्नित करें",
    "home": "होम",
    
    // Navigation Items
    "nav.overview": "अवलोकन",
    "nav.dashboard": "डैशबोर्ड",
    "nav.academic": "शैक्षणिक",
    "nav.personal.info": "व्यक्तिगत जानकारी",
    "nav.examination.record": "परीक्षा रिकॉर्ड",
    "nav.schedule": "कार्यक्रम",
    "nav.resources": "संसाधन",
    "nav.fees": "फीस",
    "nav.system": "सिस्टम",
    "nav.settings": "सेटिंग्स",
    
    // Dashboard
    "dashboard.welcome": "वापसी पर स्वागत है, अर्जुन!",
    "dashboard.overview": "आज आपकी शैक्षणिक यात्रा में क्या हो रहा है।",
    "attendance.progress": "उपस्थिति प्रगति",
    "fee.payment": "फीस भुगतान",
    "assignments": "असाइनमेंट",
    "recent.activities": "हाल की गतिविधियां",
    "upcoming.events": "आगामी कार्यक्रम",
    "quick.actions": "त्वरित कार्य",
    "view.schedule": "कार्यक्रम देखें",
    "check.fees": "फीस जांचें",
    "download.results": "परिणाम डाउनलोड करें",
    "academic.performance": "शैक्षणिक प्रदर्शन",
    "current.semester": "वर्तमान सेमेस्टर",
    "overall.grade": "समग्र ग्रेड",
    "class.rank": "कक्षा रैंक",
    
    // Personal Info
    "personal.information": "व्यक्तिगत जानकारी",
    "student.details": "छात्र विवरण",
    "full.name": "पूरा नाम",
    "roll.number": "रोल नंबर",
    "course": "कक्षा",
    "section": "वर्ग",
    "admission.number": "प्रवेश संख्या",
    "date.of.birth": "जन्म तिथि",
    "gender": "लिंग",
    "blood.group": "रक्त समूह",
    "contact.information": "संपर्क जानकारी",
    "email": "ईमेल",
    "phone": "फोन",
    "address": "पता",
    "parent.guardian.info": "माता-पिता/अभिभावक जानकारी",
    "father.name": "पिता का नाम",
    "mother.name": "माता का नाम",
    "guardian.phone": "अभिभावक फोन",
    "emergency.contact": "आपातकालीन संपर्क",
    "edit.profile": "प्रोफ़ाइल संपादित करें",
    "save.changes": "परिवर्तन सहेजें",
    
    // Examination Record
    "examination.records": "परीक्षा रिकॉर्ड",
    "exam.results": "परीक्षा परिणाम",
    "select.exam": "परीक्षा चुनें",
    "first.term": "प्रथम सत्र 2025",
    "second.term": "द्वितीय सत्र 2025",
    "annual.exam": "वार्षिक परीक्षा 2025",
    "search.subject": "विषय खोजें...",
    "subject": "विषय",
    "marks.obtained": "प्राप्त अंक",
    "total.marks": "कुल अंक",
    "percentage": "प्रतिशत",
    "grade": "ग्रेड",
    "download.transcript": "प्रतिलेख डाउनलोड करें",
    "view.detailed.report": "विस्तृत रिपोर्ट देखें",
    "exam.statistics": "परीक्षा आंकड़े",
    "highest.score": "सबसे अधिक स्कोर",
    "average.score": "औसत स्कोर",
    "subjects.passed": "उत्तीर्ण विषय",
    
    // Schedule
    "schedule.calendar": "कार्यक्रम और कैलेंडर",
    "today.schedule": "आज का कार्यक्रम",
    "upcoming.assignments": "आगामी असाइनमेंट",
    "class.timetable": "कक्षा समय सारणी",
    "monday": "सोमवार",
    "tuesday": "मंगलवार",
    "wednesday": "बुधवार",
    "thursday": "गुरुवार",
    "friday": "शुक्रवार",
    "saturday": "शनिवार",
    "sunday": "रविवार",
    "time": "समय",
    "assignment": "असाइनमेंट",
    "due.date": "देय तिथि",
    "status": "स्थिति",
    "pending": "लंबित",
    "completed": "पूर्ण",
    "submitted": "जमा किया गया",
    
    // Resources
    "learning.resources": "शिक्षा संसाधन",
    "digital.library": "डिजिटल पुस्तकालय",
    "search.resources": "संसाधन खोजें...",
    "textbooks": "पाठ्यपुस्तकें",
    "reference.books": "संदर्भ पुस्तकें",
    "online.materials": "ऑनलाइन सामग्री",
    "practice.papers": "अभ्यास पत्र",
    "download": "डाउनलोड",
    "view": "देखें",
    "recent.downloads": "हाल के डाउनलोड",
    
    // Fees
    "fee.management": "फीस प्रबंधन",
    "fee.overview": "फीस अवलोकन",
    "total.annual.fee": "कुल वार्षिक फीस",
    "paid.amount": "भुगतान की गई राशि",
    "pending.amount": "बकाया राशि",
    "payment.history": "भुगतान इतिहास",
    "quick.pay": "त्वरित भुगतान",
    "pay.now": "अभी भुगतान करें",
    "download.receipt": "रसीद डाउनलोड करें",
    "payment.due": "भुगतान बकाया",
    "fee.structure": "फीस संरचना",
    "tuition.fee": "ट्यूशन फीस",
    "exam.fee": "परीक्षा फीस",
    "library.fee": "पुस्तकालय फीस",
    "sports.fee": "खेल फीस",
    
    // Settings
    "settings": "सेटिंग्स",
    "account.settings": "खाता सेटिंग्स",
    "profile.picture": "प्रोफ़ाइल चित्र",
    "change.password": "पासवर्ड बदलें",
    "current.password": "वर्तमान पासवर्ड",
    "new.password": "नया पासवर्ड",
    "confirm.password": "पासवर्ड की पुष्टि करें",
    "preferences": "प्राथमिकताएं",
    "language": "भाषा",
    "theme": "थीम",
    "system": "सिस्टम",
    "light": "लाइट",
    "dark": "डार्क",
    "notifications.settings": "सूचना सेटिंग्स",
    "email.notifications": "ईमेल सूचनाएं",
    "push.notifications": "पुश सूचनाएं",
    "sms.notifications": "SMS सूचनाएं",
    "about.studiq": "StudIQ के बारे में",
    "company.info": "कंपनी जानकारी",
    "version": "संस्करण",
    "support": "सहायता",
    "privacy.policy": "गोपनीयता नीति",
    "terms.of.service": "सेवा की शर्तें",
    
    // Common Actions
    "save": "सहेजें",
    "edit": "संपादित करें",
    "delete": "हटाएं",
    "update": "अपडेट करें",
    "refresh": "रीफ्रेश करें",
    "loading": "लोड हो रहा है...",
    "search": "खोजें",
    "filter": "फ़िल्टर",
    "sort": "क्रमबद्ध करें",
    "export": "निर्यात करें",
    "import": "आयात करें",
    "print": "प्रिंट करें",
    "share": "साझा करें",
    "copy": "कॉपी करें",
    "close": "बंद करें",
    "back": "वापस",
    "next": "अगला",
    "previous": "पिछला",
    "submit": "जमा करें",
    "reset": "रीसेट करें",
    "clear": "साफ़ करें",
    
    // Subjects
    "english": "अंग्रेजी",
    "hindi": "हिंदी",
    "mathematics": "गणित",
    "science": "विज्ञान",
    "social.science": "सामाजिक विज्ञान",
    "physics": "भौतिक विज्ञान",
    "chemistry": "रसायन विज्ञान",
    "biology": "जीव विज्ञान",
    "geography": "भूगोल",
    "history": "इतिहास",
    "civics": "नागरिक शास्त्र",
    "computer.science": "कंप्यूटर साइंस",
    "physical.education": "शारीरिक शिक्षा",
    "art": "कला",
    "music": "संगीत",
    
    // Messages & Alerts
    "success.saved": "परिवर्तन सफलतापूर्वक सहेजे गए!",
    "error.occurred": "एक त्रुटि हुई। कृपया पुनः प्रयास करें।",
    "confirm.delete": "क्या आप वाकई इस आइटम को हटाना चाहते हैं?",
    "no.data.found": "कोई डेटा नहीं मिला",
    "loading.please.wait": "लोड हो रहा है, कृपया प्रतीक्षा करें...",
    "session.expired": "आपका सत्र समाप्त हो गया है। कृपया फिर से लॉग इन करें।",
    "connection.error": "कनेक्शन त्रुटि। कृपया अपना इंटरनेट कनेक्शन जांचें।",
    "urgent": "तत्काल",
    
    // Student Info
    "student.name": "अर्जुन सिंह",
    "student.class": "कक्षा 10-अ",
    "student.roll": "रोल नं. 015"
  },
  
  raj: {
    // App Header & Navigation - Rajasthani
    "app.title": "राजस्थान पब्लिक स्कूल",
    "app.title.hindi": "राजस्थान पब्लिक स्कूल",
    "academic.year": "पढ़ाई रो साल 2025-26",
    "quick.stats": "तुरत आंकड़ा",
    "attendance": "हाजरी",
    "fees.paid": "फीस भरगी",
    "today.classes": "आज री कक्षावां",
    "online": "ऑनलाइन",
    "light.mode": "उजाळो मोड",
    "dark.mode": "अंधेरो मोड",
    "sign.out": "साइन आउट",
    "confirm.sign.out": "साइन आउट री पुष्टि करो",
    "sign.out.message": "थे वाकई राजस्थान पब्लिक स्कूल रे छात्र पोर्टल सूं साइन आउट करणो चावो?",
    "cancel": "रद्द करो",
    "notifications": "सूचनावां",
    "mark.all.read": "सगळी नै पढ़गी मान्यो",
    "home": "घर",
    
    // Navigation Items
    "nav.overview": "देखाव",
    "nav.dashboard": "डैशबोर्ड",
    "nav.academic": "पढ़ाई रा",
    "nav.personal.info": "निजी जाणकारी",
    "nav.examination.record": "परीक्षा रिकॉर्ड",
    "nav.schedule": "कार्यक्रम",
    "nav.resources": "साधन",
    "nav.fees": "फीस",
    "nav.system": "सिस्टम",
    "nav.settings": "सेटिंग्स",
    
    // Dashboard
    "dashboard.welcome": "वापसी माय खुशी, अर्जुन!",
    "dashboard.overview": "आज थारी पढ़ाई में के हो रह्यो है।",
    "attendance.progress": "हाजरी री बढ़त",
    "fee.payment": "फीस भरणी",
    "assignments": "काम",
    "recent.activities": "हाली री गतिविधियां",
    "upcoming.events": "आण वाला कार्यक्रम",
    "quick.actions": "तुरत काम",
    "view.schedule": "कार्यक्रम देखो",
    "check.fees": "फीस जांचो",
    "download.results": "नतीजा डाउनलोड करो",
    "academic.performance": "पढ़ाई रो प्रदर्शन",
    "current.semester": "इब रो सेमेस्टर",
    "overall.grade": "कुल ग्रेड",
    "class.rank": "कक्षा रैंक",
    
    // Personal Info
    "personal.information": "निजी जाणकारी",
    "student.details": "छात्र री जाणकारी",
    "full.name": "पूरो नाम",
    "roll.number": "रोल नंबर",
    "course": "कक्षा",
    "section": "भाग",
    "admission.number": "दाखिला नंबर",
    "date.of.birth": "जन्म री तारीख",
    "gender": "लिंग",
    "blood.group": "खून रो समूह",
    "contact.information": "संपर्क री जाणकारी",
    "email": "ईमेल",
    "phone": "फोन",
    "address": "पतो",
    "parent.guardian.info": "मा-बाप/संरक्षक री जाणकारी",
    "father.name": "बापू रो नाम",
    "mother.name": "मा रो नाम",
    "guardian.phone": "संरक्षक रो फोन",
    "emergency.contact": "आपातकाल संपर्क",
    "edit.profile": "प्रोफाइल सुधारो",
    "save.changes": "बदलाव बचाओ",
    "profile.picture": "प्रोफाइल री तस्वीर",
    
    // Examination Record
    "examination.records": "परीक्षा रिकॉर्ड",
    "exam.results": "परीक्षा रा नतीजा",
    "select.exam": "परीक्षा चुणो",
    "first.term": "पैली बार 2025",
    "second.term": "दूसरी बार 2025",
    "annual.exam": "सालाना परीक्षा 2025",
    "search.subject": "विषय खोजो...",
    "subject": "विषय",
    "marks.obtained": "मिल्या अंक",
    "total.marks": "कुल अंक",
    "percentage": "प्रतिशत",
    "grade": "ग्रेड",
    "download.transcript": "प्रतिलेख डाउनलोड करो",
    "view.detailed.report": "विस्तार सूं रिपोर्ट देखो",
    
    // Schedule
    "schedule.calendar": "कार्यक्रम अर कैलेंडर",
    "today.schedule": "आज रो कार्यक्रम",
    "upcoming.assignments": "आण वाला काम",
    "class.timetable": "कक्षा रो समय",
    "monday": "सोमवार",
    "tuesday": "मंगळवार",
    "wednesday": "बुधवार",
    "thursday": "गुरुवार",
    "friday": "शुक्रवार",
    "saturday": "शनिवार",
    "sunday": "रविवार",
    "time": "समय",
    "assignment": "काम",
    "due.date": "देय तारीख",
    "status": "स्थिति",
    "pending": "बाकी",
    "completed": "पूरो",
    "submitted": "जमा करग्यो",
    
    // Resources
    "learning.resources": "पढ़ाई रा साधन",
    "digital.library": "डिजिटल लाइब्रेरी",
    "search.resources": "साधन खोजो...",
    "textbooks": "पाठ्यपुस्तकां",
    "reference.books": "संदर्भ पुस्तकां",
    "online.materials": "ऑनलाइन सामग्री",
    "practice.papers": "अभ्यास पत्र",
    "download": "डाउनलोड करो",
    "view": "देखो",
    "recent.downloads": "हाली रा डाउनलोड",
    
    // Fees
    "fee.management": "फीस व्यवस्था",
    "fee.overview": "फीस रो देखाव",
    "total.annual.fee": "कुल सालाना फीस",
    "paid.amount": "भरी राशि",
    "pending.amount": "बाकी राशि",
    "payment.history": "भुगतान रो इतिहास",
    "quick.pay": "तुरत भुगतान",
    "pay.now": "अब भरो",
    "download.receipt": "रसीद डाउनलोड करो",
    "payment.due": "भुगतान बाकी",
    "fee.structure": "फीस री संरचना",
    "tuition.fee": "शिक्षा फीस",
    "exam.fee": "परीक्षा फीस",
    "library.fee": "लाइब्रेरी फीस",
    "sports.fee": "खेल फीस",
    
    // Settings
    "settings": "सेटिंग्स",
    "account.settings": "खाता सेटिंग्स",
    "change.password": "पासवर्ड बदलो",
    "current.password": "इब रो पासवर्ड",
    "new.password": "नवो पासवर्ड",
    "confirm.password": "पासवर्ड री पुष्टि करो",
    "preferences": "पसंद",
    "language": "भाषा",
    "theme": "थीम",
    "system": "सिस्टम",
    "light": "उजाळो",
    "dark": "अंधेरो",
    "notifications.settings": "सूचना सेटिंग्स",
    "email.notifications": "ईमेल सूचनावां",
    "push.notifications": "पुश सूचनावां",
    "sms.notifications": "SMS सूचनावां",
    
    // Common Actions
    "save": "बचाओ",
    "edit": "सुधारो",
    "delete": "मिटाओ",
    "update": "अपडेट करो",
    "refresh": "रिफ्रेश करो",
    "loading": "लोड हो रह्यो है...",
    "search": "खोजो",
    "filter": "फिल्टर",
    "sort": "क्रमबद्ध करो",
    "export": "निर्यात करो",
    "import": "आयात करो",
    "print": "प्रिंट करो",
    "share": "साझा करो",
    "copy": "कॉपी करो",
    "close": "बंद करो",
    "back": "वापस",
    "next": "अगलो",
    "previous": "पिछलो",
    "submit": "जमा करो",
    "reset": "रीसेट करो",
    "clear": "साफ करो",
    
    // Subjects
    "english": "अंग्रेजी",
    "hindi": "हिंदी",
    "mathematics": "गणित",
    "science": "विज्ञान",
    "social.science": "सामाजिक विज्ञान",
    "physics": "भौतिक विज्ञान",
    "chemistry": "रसायन विज्ञान",
    "biology": "जीव विज्ञान",
    "geography": "भूगोल",
    "history": "इतिहास",
    "civics": "नागरिक शास्त्र",
    "computer.science": "कंप्यूटर साइंस",
    "physical.education": "शारीरिक शिक्षा",
    "art": "कला",
    "music": "संगीत",
    
    // Messages & Alerts
    "success.saved": "बदलाव सफलता सूं बचग्या!",
    "error.occurred": "कोई त्रुटि होगी। फेर कोशिश करो।",
    "confirm.delete": "थे वाकई इस चीज नै मिटाणो चावो?",
    "no.data.found": "कोई डेटा कोनी मिल्यो",
    "loading.please.wait": "लोड हो रह्यो है, रुको...",
    "session.expired": "थारो सत्र खतम होग्यो। फेर लॉग इन करो।",
    "connection.error": "कनेक्शन में दिक्कत। इंटरनेट जांचो।",
    
    // Student Info
    "student.name": "अर्जुन सिंह",
    "student.class": "कक्षा 10-अ",
    "student.roll": "रोल नं. 015"
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>("en");

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language;
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}